
# Redirect HTTP to HTTPS
  server {
    if ($host = rhaitech.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = www.rhaitech.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

      listen 80;
     server_name rhaitech.online www.rhaitech.online;
     return 301 https://$host$request_uri;
 


}


# HTTPS server
  server {
    listen 443 ssl;
    server_name rhaitech.online www.rhaitech.online;

    root /app/Rhaitech;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
    ssl_certificate /etc/letsencrypt/live/rhaitech.online/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/rhaitech.online/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}




# ActiveLife Hospital App
# HTTP (for Certbot + redirect)
server {
    listen 80;
    server_name hospitalactivelife.rhaitech.online;

    return 301 https://$host$request_uri;
}

# HTTPS (TEMP placeholder - Certbot will update SSL later)
server {
    listen 443 ssl;
    server_name hospitalactivelife.rhaitech.online;

 location / {
        proxy_pass http://localhost:5002;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    ssl_certificate /etc/letsencrypt/live/hospitalactivelife.rhaitech.online/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hospitalactivelife.rhaitech.online/privkey.pem; # managed by Certbot
}



# InstituteManagement backend
server {
    server_name institute-api.rhaitech.online;

    location /arise/ {
        rewrite ^/arise/(.*) /$1 break;
        proxy_pass http://localhost:5003;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        proxy_pass http://localhost:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/institute-api.rhaitech.online/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/institute-api.rhaitech.online/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = institute-api.rhaitech.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name institute-api.rhaitech.online;
    return 404; # managed by Certbot
}



server {
    if ($host = rhaitech.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name rhaitech.online www.rhaitech.online;
    return 404; # managed by Certbot


}

server {
    if ($host = hospitalactivelife.rhaitech.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name hospitalactivelife.rhaitech.online;
    listen 80;
    return 404; # managed by Certbot


}
